Finished grooming game loop
abdrdg/Foundry pull request #64
Opened 2023-06-27 02:49 UTC by johnzillakaiju

still need to add sprite changes at certain HP threshold and polish

2023-06-27 03:01 UTC, VeoWulfOfWallSt requested changes, later dismissed
Able to use the tools when the curtain is u

2023-06-27 03:02 UTC, khmflrdlz approved these changes
No issue with tool changes. the game loop is working properly.
Pull Request approved.

2023-07-03 09:03 UTC, abdrdg approved these changes

2023-07-03 09:11 UTC, VeoWulfOfWallSt approved these changes
General Gameplay loop is working, Approving for now

Known Issue: The user is still able to use the tool during tool transitions

2023-07-03 09:12 UTC, merged